RouteOptimize_WEB/Controllers/RouteController.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RouteOptimize_WEB.Models;
using System.Configuration;
using FastMember;
using Newtonsoft.Json;
using System.IO;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Drawing;

namespace RouteOptimize_WEB.Controllers
{
    public class RouteController : Controller
    {
        private string TmsConnectionString = ConfigurationManager.ConnectionStrings["DISPOPRD"].ConnectionString;
        private static clsMySQLConnection mysqlCon = new clsMySQLConnection();

        //private int maxPerRoute = 59;
        private DataTable dtActualRoute = new DataTable();
        private DataTable dtActualRouteSingle = new DataTable();
        private DataTable dtOriginalOrder = new DataTable();
        private DataTable dtFirstMain = new DataTable();
        private DataTable dtFirstMainSingle = new DataTable();

        // GET: Route
        public ActionResult Index()
        {
            var data = mysqlCon.GetDataTable("select distinct orderdate from sampleorder group by orderdate order by orderdate desc", "sampleorder");
            return View(data.AsEnumerable().ToList());
        }

        public ActionResult List()
        {
            return View();
        }

        public ActionResult ReadExcel()
        {
            return View();
        }

        public ActionResult _RouteTable(int totalTruck = 43)
        {
            //DataTable dtActualRoute = new DataTable();
            //DataTable dtFirstMain = GetRouteData();

            //DataTable dtFirstMainSingle = new DataTable();
            //dtFirstMainSingle = dtFirstMain.Select("IsSingleRoute =1").CopyToDataTable();
            //dtFirstMain.AcceptChanges();

            ////Single route
            //var groupedData = (from b in dtFirstMainSingle.AsEnumerable()
            //                   group b by b.Field<string>("routecode_thunder") into g
            //                   //(x => new { Team = x.team, Status = x.status })
            //                   let list = g.ToList()
            //                   select new
            //                   {

            //                       IsRouteComplete = list.Count == maxPerRoute ? true : false,
            //                       MainRoute = g.Key,

            //                       GrandTotalStore = list.Count,
            //                       MainRouteStore = list.Count,
            //                       storeListlist = list.CopyToDataTable<DataRow>(),
            //                       LastHustle = g.Key,
            //                       SuggestRoute = string.Format("({0})", g.Key),
            //                       IsHeavyRoute = false,
            //                       IsSingleRoute = true,
            //                       RemainStore = string.Empty,
            //                       TotalQty = list.CopyToDataTable<DataRow>().Compute("SUM(QTY)", string.Empty)


            //                   }).OrderByDescending(t => t.GrandTotalStore)
            //                  .ToList();



            //using (var reader = ObjectReader.Create(groupedData))
            //{
            //    dtActualRoute.Load(reader);
            //    dtActualRoute.AcceptChanges();
            //}

            ////Multi route
            //var groupedData2 = (from b in dtFirstMain.AsEnumerable()
            //               group b by b.Field<string>("routecode_thunder") into g
            //               //(x => new { Team = x.team, Status = x.status })
            //               let list = g.ToList()
            //               select new
            //               {

            //                   /*0*/
            //                   IsRouteComplete = list.Count == maxPerRoute ? true : false,
            //                   /*1*/
            //                   MainRoute = g.Key,
            //                   /*2*/
            //                   GrandTotalStore = list.Count,
            //                   /*3*/
            //                   MainRouteStore = list.Count,
            //                   /*4*/
            //                   storeListlist = list.CopyToDataTable<DataRow>(),
            //                   /*5*/
            //                   LastHustle = g.Key,
            //                   /*6*/
            //                   SuggestRoute = string.Format("({0})", g.Key),
            //                   /*7*/
            //                   IsHeavyRoute = false,
            //                   /*8*/
            //                   IsSingleRoute = false,
            //                   /*9*/
            //                   RemainStore = string.Empty,
            //                   /*10*/
            //                   TotalQty = list.CopyToDataTable<DataRow>().Compute("SUM(QTY)", string.Empty)


            //               }).OrderByDescending(t => t.GrandTotalStore)
            //                  .Take(totalTruck - dtActualRoute.Rows.Count)
            //                  .ToList();


            //using (var reader = ObjectReader.Create(groupedData2))
            //{
            //    dtActualRoute.Load(reader);
            //    dtActualRoute.AcceptChanges();
            //}
            //int countRow = dtActualRoute.Rows.Count;

            //var data = dtActualRoute.AsEnumerable().OrderByDescending(o => o.ItemArray[2]).ToList();
            //return PartialView(data);
            return PartialView();
        }

        public ActionResult _UnplanRouteTable(int totalTruck = 43)
        {
         //   DataTable dtActualRoute = new DataTable();
         //   DataTable dtUnplanRoute = new DataTable();
         //   DataTable dtFirstMain = GetRouteData();

         //   DataTable dtFirstMainSingle = new DataTable();
         //   dtFirstMainSingle = dtFirstMain.Select("IsSingleRoute =1").CopyToDataTable();


         //   dtUnplanRoute = dtFirstMain.Select("routecode_thunder is null").CopyToDataTable();
         //   dtFirstMain = dtFirstMain.Select("IsSingleRoute <>1").CopyToDataTable();
         //   //filter out null prefer route
         //   /*foreach (DataRow row in drArrayFirst)
         //   {
         //       dtUnplanRoute.Rows.Add(row.ItemArray);
         //       row.Delete();
         //   }*/
         //   dtFirstMain.AcceptChanges();
         //   dtUnplanRoute.AcceptChanges();

         //   //Single route
         //   var groupedData = (from b in dtFirstMainSingle.AsEnumerable()
         //                      group b by b.Field<string>("routecode_thunder") into g
         //                      //(x => new { Team = x.team, Status = x.status })
         //                      let list = g.ToList()
         //                      select new
         //                      {

         //                          IsRouteComplete = list.Count == maxPerRoute ? true : false,
         //                          MainRoute = g.Key,

         //                          GrandTotalStore = list.Count,
         //                          MainRouteStore = list.Count,
         //                          storeListlist = list.CopyToDataTable<DataRow>(),
         //                          LastHustle = g.Key,
         //                          SuggestRoute = string.Format("({0})", g.Key),
         //                          IsHeavyRoute = false,
         //                          IsSingleRoute = true,
         //                          RemainStore = string.Empty,
         //                          TotalQty = list.CopyToDataTable<DataRow>().Compute("SUM(QTY)", string.Empty)


         //                      }).OrderByDescending(t => t.GrandTotalStore)
         //                     .ToList();



         //   using (var reader = ObjectReader.Create(groupedData))
         //   {
         //       dtActualRoute.Load(reader);
         //       dtActualRoute.AcceptChanges();
         //   }

         //   //Multi route
         //   var groupedData2 = (from b in dtFirstMain.AsEnumerable()
         //                       group b by b.Field<string>("routecode_thunder") into g
         //                       //(x => new { Team = x.team, Status = x.status })
         //                       let list = g.ToList()
         //                       select new
         //                       {

         //                           /*0*/
         //                           IsRouteComplete = list.Count == maxPerRoute ? true : false,
         //                           /*1*/
         //                           MainRoute = g.Key,
         //                           /*2*/
         //                           GrandTotalStore = list.Count,
         //                           /*3*/
         //                           MainRouteStore = list.Count,
         //                           /*4*/
         //                           storeListlist = list.CopyToDataTable<DataRow>(),
         //                           /*5*/
         //                           LastHustle = g.Key,
         //                           /*6*/
         //                           SuggestRoute = string.Format("({0})", g.Key),
         //                           /*7*/
         //                           IsHeavyRoute = false,
         //                           /*8*/
         //                           IsSingleRoute = false,
         //                           /*9*/
         //                           RemainStore = string.Empty,
         //                           /*10*/
         //                           TotalQty = list.CopyToDataTable<DataRow>().Compute("SUM(QTY)", string.Empty)


         //                       }).OrderByDescending(t => t.GrandTotalStore)
         //                     .Take(totalTruck - dtActualRoute.Rows.Count)
         //                     .ToList();

RouteOptimize_WEB/Views/Route/List.cshtml
@{
    ViewBag.Title = "List";
}

<h2>List</h2>

RouteOptimize_WEB/Views/Route/ReadExcel.cshtml
@{
    ViewBag.Title = "ReadExcel";
}

<style>
    blockquote {
        background: #B9DFF1;
        margin: 0px 50px 0px 50px;
        padding: 30px 30px 30px 50px;
        color: #4797aa;
        border-radius: 15px;
        font-size: 20px;
        font: bold 0.9em “Comic Sans MS”, verdana;
        line-height: 1.6em;
        box-shadow: 4px 4px 10px #e3e3e3;
        border-left: 9px solid;
        /*position: relative;
        top: 30px;
        z-index: 100;
        border-right: 9px solid;*/
    }
</style>
<blockquote>
    <h4><i class="fa fa-star" aria-hidden="true"></i> Import Route Optimize</h4>
    <p class="m-0">Please import thunder route file!</p>
    <p class="m-0"><code>*<small>Program will read data from row at 2 & column at 1</small></code></p>
</blockquote>
<hr />
<form method="post" action="@Url.Action("SaveImportRoute", "Route")" enctype="multipart/form-data">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="customFile" name="fileRoute">
                        <label class="custom-file-label" for="customFile">Choose file</label>
                    </div>
                    <p class="m-0 text-right mt-4">
                        <button class="btn btn-primary"><i class="fa fa-floppy-o"></i> Import</button>
                    </p>
                </div>
            </div>
        </div>
    </div>
</form>

RouteOptimize_WEB/Views/Route/_RouteTable.cshtml
@{
    ViewBag.Title = "_RouteTable";
}
@*@model  List<System.Data.DataRow>*@

<h4 data-toggle="collapse" data-target="#divRoute" aria-expanded="false" aria-controls="divRoute">New Route <i class="fa"></i></h4>
<div id="divRoute" class="collapse">
    <table class="table table-sm cupid-blue minimal" id="tbRoute">
        <thead>
            <tr>
                <th>GrandTotalStore</th>
                <th>IsHeavyRoute</th>
                <th>IsRouteComplete</th>
                <th>IsSingleRoute</th>
                <th>LastHustle</th>
                <th>MainRoute</th>
                <th>MainRouteStore</th>
                <th>RemainStore</th>
                @*<th>StoreList</th>*@
                <th>SuggestRoute</th>
                <th>TotalQty</th>
            </tr>
        </thead>
        <tbody>
            @*@if (Model.Count() > 0)
                {
                    int countRows = 1;
                    foreach (var a in Model)
                    {
                <tr>
                    <td class="text-center">@a.ItemArray[2]</td>
                    <td class="text-center">
                        <input type="checkbox" class="custom-control-input cbHeavyRoute" @if (a.ItemArray[7].ToString() != "false"){ <text> checked</text>}>
                    </td>
                    <td>
                        <input type="checkbox" class="custom-control-input cbRouteComplete" @if (a.ItemArray[0].ToString() != "false"){ <text> checked</text>}>

                    </td>
                    <td class="text-center">
                        <input type="checkbox" class="custom-control-input cbSingleRoute" @if (a.ItemArray[8].ToString() != "false"){ <text> checked</text>}>
                    </td>
                    <td class="text-center">@a.ItemArray[5]</td>
                    <td class="text-center">@a.ItemArray[1]</td>
                    <td class="text-center">@a.ItemArray[3]</td>
                    <td class="text-center">@a.ItemArray[4]</td>
                    <td class="text-center">@a.ItemArray[9]</td>
                    <td class="text-center">@a.ItemArray[6]</td>
                    <td class="text-center">@a.ItemArray[10]</td>
                </tr>

                        countRows++;
                    }
                }
                else
                {
                    <tr>
                        <td colspan="11" class="text-center">No data.</td>
                    </tr>
                }*@
        </tbody>
    </table>
</div>

RouteOptimize_WEB/Views/Route/_UnplanRouteTable.cshtml
@{
    ViewBag.Title = "_UnplanRouteTable";
}

<h4 data-toggle="collapse" data-target="#divUnplanRoute" aria-expanded="false" aria-controls="divUnplanRoute">Unplan Route <i class="fa"></i></h4>
<div id="divUnplanRoute" class="collapse">
    <table class="table table-sm cupid-blue minimal" id="tbUnplanRoute">
        <thead>
            <tr>
                <th>Route Code Thunder</th>
                <th>Prefer 1</th>
                <th>Prefer 2</th>
                <th>Prefer 3</th>
                <th>Prefer 4</th>
                <th>Store Code</th>
                <th>Qty</th>
                <th>IsSingleRoute</th>
                <th>Sub Total</th>
                <th>Sub Total 1</th>
            </tr>
        </thead>
        <tbody>
            @*@if (Model.Count() > 0)
                {
                    int countRows = 1;
                    foreach (var a in Model)
                    {
                <tr>
                    <td class="text-center">@a.ItemArray[2]</td>
                    <td class="text-center">
                        <input type="checkbox" class="custom-control-input cbHeavyRoute" @if (a.ItemArray[7].ToString() != "false"){ <text> checked</text>}>
                    </td>
                    <td>
                        <input type="checkbox" class="custom-control-input cbRouteComplete" @if (a.ItemArray[0].ToString() != "false"){ <text> checked</text>}>

                    </td>
                    <td class="text-center">
                        <input type="checkbox" class="custom-control-input cbSingleRoute" @if (a.ItemArray[8].ToString() != "false"){ <text> checked</text>}>
                    </td>
                    <td class="text-center">@a.ItemArray[5]</td>
                    <td class="text-center">@a.ItemArray[1]</td>
                    <td class="text-center">@a.ItemArray[3]</td>
                    <td class="text-center">@a.ItemArray[4]</td>
                    <td class="text-center">@a.ItemArray[9]</td>
                    <td class="text-center">@a.ItemArray[6]</td>
                    <td class="text-center">@a.ItemArray[10]</td>
                </tr>

                        countRows++;
                    }
                }
                else
                {
                    <tr>
                        <td colspan="11" class="text-center">No data.</td>
                    </tr>
                }*@
        </tbody>
    </table>
</div>